# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def CategorizeOnly(self, title: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CategorizeOnlyResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CategorizeOnly(title=title,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CategorizeOnly", args={
                "title": title,
            })
            return typing.cast(types.CategorizeOnlyResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyKind(self, title: str,url: str,summary: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ClassifyKindResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyKind(title=title,url=url,summary=summary,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyKind", args={
                "title": title,"url": url,"summary": summary,
            })
            return typing.cast(types.ClassifyKindResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyProfiles(self, profiles: typing.List["types.ProfileInput"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ProfileVerdict"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyProfiles(profiles=profiles,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyProfiles", args={
                "profiles": profiles,
            })
            return typing.cast(typing.List["types.ProfileVerdict"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractLinks(self, emailHtml: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ExtractedLink"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractLinks(emailHtml=emailHtml,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractLinks", args={
                "emailHtml": emailHtml,
            })
            return typing.cast(typing.List["types.ExtractedLink"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractProducts(self, newsletterText: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.NewsletterProduct"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractProducts(newsletterText=newsletterText,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractProducts", args={
                "newsletterText": newsletterText,
            })
            return typing.cast(typing.List["types.NewsletterProduct"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ImproveTitles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.TitleFix"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ImproveTitles(articles=articles,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ImproveTitles", args={
                "articles": articles,
            })
            return typing.cast(typing.List["types.TitleFix"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ScoreArticles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ScoredArticle"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ScoreArticles(articles=articles,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ScoreArticles", args={
                "articles": articles,
            })
            return typing.cast(typing.List["types.ScoredArticle"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SelectNotableProducts(self, products: typing.List["types.NewsletterProduct"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List[int]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SelectNotableProducts(products=products,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SelectNotableProducts", args={
                "products": products,
            })
            return typing.cast(typing.List[int], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SelectProductLink(self, productName: str,productDescription: str,candidates: typing.List["types.SearchCandidate"],
        baml_options: BamlCallOptions = {},
    ) -> types.ProductLinkChoice:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SelectProductLink(productName=productName,productDescription=productDescription,candidates=candidates,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SelectProductLink", args={
                "productName": productName,"productDescription": productDescription,"candidates": candidates,
            })
            return typing.cast(types.ProductLinkChoice, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SemanticDedup(self, newArticles: typing.List["types.ArticleInput"],existingArticles: typing.List["types.ExistingArticle"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.DedupMatch"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SemanticDedup(newArticles=newArticles,existingArticles=existingArticles,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SemanticDedup", args={
                "newArticles": newArticles,"existingArticles": existingArticles,
            })
            return typing.cast(typing.List["types.DedupMatch"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SummarizeAndCategorize(self, title: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SummarizeAndCategorizeResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SummarizeAndCategorize(title=title,content=content,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SummarizeAndCategorize", args={
                "title": title,"content": content,
            })
            return typing.cast(types.SummarizeAndCategorizeResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CategorizeOnly(self, title: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CategorizeOnlyResult, types.CategorizeOnlyResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CategorizeOnly", args={
            "title": title,
        })
        return baml_py.BamlStream[stream_types.CategorizeOnlyResult, types.CategorizeOnlyResult](
          __result__,
          lambda x: typing.cast(stream_types.CategorizeOnlyResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CategorizeOnlyResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyKind(self, title: str,url: str,summary: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClassifyKindResult, types.ClassifyKindResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyKind", args={
            "title": title,"url": url,"summary": summary,
        })
        return baml_py.BamlStream[stream_types.ClassifyKindResult, types.ClassifyKindResult](
          __result__,
          lambda x: typing.cast(stream_types.ClassifyKindResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassifyKindResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyProfiles(self, profiles: typing.List["types.ProfileInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.ProfileVerdict"], typing.List["types.ProfileVerdict"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyProfiles", args={
            "profiles": profiles,
        })
        return baml_py.BamlStream[typing.List["stream_types.ProfileVerdict"], typing.List["types.ProfileVerdict"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.ProfileVerdict"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ProfileVerdict"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractLinks(self, emailHtml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.ExtractedLink"], typing.List["types.ExtractedLink"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractLinks", args={
            "emailHtml": emailHtml,
        })
        return baml_py.BamlStream[typing.List["stream_types.ExtractedLink"], typing.List["types.ExtractedLink"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.ExtractedLink"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ExtractedLink"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractProducts(self, newsletterText: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.NewsletterProduct"], typing.List["types.NewsletterProduct"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractProducts", args={
            "newsletterText": newsletterText,
        })
        return baml_py.BamlStream[typing.List["stream_types.NewsletterProduct"], typing.List["types.NewsletterProduct"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.NewsletterProduct"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.NewsletterProduct"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ImproveTitles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.TitleFix"], typing.List["types.TitleFix"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ImproveTitles", args={
            "articles": articles,
        })
        return baml_py.BamlStream[typing.List["stream_types.TitleFix"], typing.List["types.TitleFix"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.TitleFix"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.TitleFix"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ScoreArticles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.ScoredArticle"], typing.List["types.ScoredArticle"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ScoreArticles", args={
            "articles": articles,
        })
        return baml_py.BamlStream[typing.List["stream_types.ScoredArticle"], typing.List["types.ScoredArticle"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.ScoredArticle"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.ScoredArticle"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SelectNotableProducts(self, products: typing.List["types.NewsletterProduct"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List[int], typing.List[int]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SelectNotableProducts", args={
            "products": products,
        })
        return baml_py.BamlStream[typing.List[int], typing.List[int]](
          __result__,
          lambda x: typing.cast(typing.List[int], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List[int], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SelectProductLink(self, productName: str,productDescription: str,candidates: typing.List["types.SearchCandidate"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ProductLinkChoice, types.ProductLinkChoice]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SelectProductLink", args={
            "productName": productName,"productDescription": productDescription,"candidates": candidates,
        })
        return baml_py.BamlStream[stream_types.ProductLinkChoice, types.ProductLinkChoice](
          __result__,
          lambda x: typing.cast(stream_types.ProductLinkChoice, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ProductLinkChoice, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SemanticDedup(self, newArticles: typing.List["types.ArticleInput"],existingArticles: typing.List["types.ExistingArticle"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.DedupMatch"], typing.List["types.DedupMatch"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SemanticDedup", args={
            "newArticles": newArticles,"existingArticles": existingArticles,
        })
        return baml_py.BamlStream[typing.List["stream_types.DedupMatch"], typing.List["types.DedupMatch"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.DedupMatch"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.DedupMatch"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SummarizeAndCategorize(self, title: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SummarizeAndCategorizeResult, types.SummarizeAndCategorizeResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SummarizeAndCategorize", args={
            "title": title,"content": content,
        })
        return baml_py.BamlStream[stream_types.SummarizeAndCategorizeResult, types.SummarizeAndCategorizeResult](
          __result__,
          lambda x: typing.cast(stream_types.SummarizeAndCategorizeResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SummarizeAndCategorizeResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CategorizeOnly(self, title: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CategorizeOnly", args={
            "title": title,
        }, mode="request")
        return __result__
    async def ClassifyKind(self, title: str,url: str,summary: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyKind", args={
            "title": title,"url": url,"summary": summary,
        }, mode="request")
        return __result__
    async def ClassifyProfiles(self, profiles: typing.List["types.ProfileInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyProfiles", args={
            "profiles": profiles,
        }, mode="request")
        return __result__
    async def ExtractLinks(self, emailHtml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractLinks", args={
            "emailHtml": emailHtml,
        }, mode="request")
        return __result__
    async def ExtractProducts(self, newsletterText: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractProducts", args={
            "newsletterText": newsletterText,
        }, mode="request")
        return __result__
    async def ImproveTitles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ImproveTitles", args={
            "articles": articles,
        }, mode="request")
        return __result__
    async def ScoreArticles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ScoreArticles", args={
            "articles": articles,
        }, mode="request")
        return __result__
    async def SelectNotableProducts(self, products: typing.List["types.NewsletterProduct"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SelectNotableProducts", args={
            "products": products,
        }, mode="request")
        return __result__
    async def SelectProductLink(self, productName: str,productDescription: str,candidates: typing.List["types.SearchCandidate"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SelectProductLink", args={
            "productName": productName,"productDescription": productDescription,"candidates": candidates,
        }, mode="request")
        return __result__
    async def SemanticDedup(self, newArticles: typing.List["types.ArticleInput"],existingArticles: typing.List["types.ExistingArticle"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SemanticDedup", args={
            "newArticles": newArticles,"existingArticles": existingArticles,
        }, mode="request")
        return __result__
    async def SummarizeAndCategorize(self, title: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SummarizeAndCategorize", args={
            "title": title,"content": content,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CategorizeOnly(self, title: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CategorizeOnly", args={
            "title": title,
        }, mode="stream")
        return __result__
    async def ClassifyKind(self, title: str,url: str,summary: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyKind", args={
            "title": title,"url": url,"summary": summary,
        }, mode="stream")
        return __result__
    async def ClassifyProfiles(self, profiles: typing.List["types.ProfileInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyProfiles", args={
            "profiles": profiles,
        }, mode="stream")
        return __result__
    async def ExtractLinks(self, emailHtml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractLinks", args={
            "emailHtml": emailHtml,
        }, mode="stream")
        return __result__
    async def ExtractProducts(self, newsletterText: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractProducts", args={
            "newsletterText": newsletterText,
        }, mode="stream")
        return __result__
    async def ImproveTitles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ImproveTitles", args={
            "articles": articles,
        }, mode="stream")
        return __result__
    async def ScoreArticles(self, articles: typing.List["types.ArticleInput"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ScoreArticles", args={
            "articles": articles,
        }, mode="stream")
        return __result__
    async def SelectNotableProducts(self, products: typing.List["types.NewsletterProduct"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SelectNotableProducts", args={
            "products": products,
        }, mode="stream")
        return __result__
    async def SelectProductLink(self, productName: str,productDescription: str,candidates: typing.List["types.SearchCandidate"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SelectProductLink", args={
            "productName": productName,"productDescription": productDescription,"candidates": candidates,
        }, mode="stream")
        return __result__
    async def SemanticDedup(self, newArticles: typing.List["types.ArticleInput"],existingArticles: typing.List["types.ExistingArticle"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SemanticDedup", args={
            "newArticles": newArticles,"existingArticles": existingArticles,
        }, mode="stream")
        return __result__
    async def SummarizeAndCategorize(self, title: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SummarizeAndCategorize", args={
            "title": title,"content": content,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))