# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CategorizeOnly(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CategorizeOnlyResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CategorizeOnly", llm_response=llm_response, mode="request")
        return typing.cast(types.CategorizeOnlyResult, __result__)

    def ClassifyKind(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClassifyKindResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyKind", llm_response=llm_response, mode="request")
        return typing.cast(types.ClassifyKindResult, __result__)

    def ClassifyProfiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ProfileVerdict"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyProfiles", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.ProfileVerdict"], __result__)

    def ExtractLinks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ExtractedLink"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractLinks", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.ExtractedLink"], __result__)

    def ExtractProducts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.NewsletterProduct"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProducts", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.NewsletterProduct"], __result__)

    def ImproveTitles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.TitleFix"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ImproveTitles", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.TitleFix"], __result__)

    def ScoreArticles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ScoredArticle"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreArticles", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.ScoredArticle"], __result__)

    def SelectNotableProducts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[int]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectNotableProducts", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[int], __result__)

    def SelectProductLink(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ProductLinkChoice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectProductLink", llm_response=llm_response, mode="request")
        return typing.cast(types.ProductLinkChoice, __result__)

    def SemanticDedup(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.DedupMatch"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SemanticDedup", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.DedupMatch"], __result__)

    def SummarizeAndCategorize(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SummarizeAndCategorizeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeAndCategorize", llm_response=llm_response, mode="request")
        return typing.cast(types.SummarizeAndCategorizeResult, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CategorizeOnly(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CategorizeOnlyResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CategorizeOnly", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CategorizeOnlyResult, __result__)

    def ClassifyKind(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClassifyKindResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyKind", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClassifyKindResult, __result__)

    def ClassifyProfiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.ProfileVerdict"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyProfiles", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.ProfileVerdict"], __result__)

    def ExtractLinks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.ExtractedLink"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractLinks", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.ExtractedLink"], __result__)

    def ExtractProducts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.NewsletterProduct"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProducts", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.NewsletterProduct"], __result__)

    def ImproveTitles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.TitleFix"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ImproveTitles", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.TitleFix"], __result__)

    def ScoreArticles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.ScoredArticle"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreArticles", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.ScoredArticle"], __result__)

    def SelectNotableProducts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[int]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectNotableProducts", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[int], __result__)

    def SelectProductLink(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ProductLinkChoice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectProductLink", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ProductLinkChoice, __result__)

    def SemanticDedup(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.DedupMatch"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SemanticDedup", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.DedupMatch"], __result__)

    def SummarizeAndCategorize(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SummarizeAndCategorizeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeAndCategorize", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SummarizeAndCategorizeResult, __result__)

    