# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (14)
# #########################################################################

class ArticleInput(BaseModel):
    url: typing.Optional[str] = None
    title: typing.Optional[str] = None
    source: typing.Optional[str] = None
    snippet: typing.Optional[str] = Field(default=None, description='First ~200 chars of the article content, if any')
    trust: typing.Optional[str] = Field(default=None, description='"high" | "medium" | "low" - source trust tag')

class CategorizeOnlyResult(BaseModel):
    categories: typing.List[types.ArticleCategory] = Field(description='1-2 categories')

class ClassifyKindResult(BaseModel):
    kind: typing.Optional[types.ArticleKind] = None

class DedupMatch(BaseModel):
    url: typing.Optional[str] = Field(default=None, description='URL of the new article')
    existingUrl: typing.Optional[str] = Field(default=None, description='URL of the existing article it duplicates')

class ExistingArticle(BaseModel):
    url: typing.Optional[str] = None
    title: typing.Optional[str] = None
    source: typing.Optional[str] = None

class ExtractedLink(BaseModel):
    title: typing.Optional[str] = None
    url: typing.Optional[str] = None
    snippet: typing.Optional[str] = Field(default=None, description='One-sentence description of the article')

class NewsletterProduct(BaseModel):
    name: typing.Optional[str] = Field(default=None, description='Exact product / tool / model / launch name')
    description: typing.Optional[str] = Field(default=None, description='Concise phrase: what it is and does, usable verbatim as a web search query')

class ProductLinkChoice(BaseModel):
    index: typing.Optional[int] = Field(default=None, description='1-based index of the best first-party result, or 0 if none qualifies')
    confidence: typing.Optional[float] = Field(default=None, description='0.0 - 1.0')

class ProfileInput(BaseModel):
    handle: typing.Optional[str] = Field(default=None, description='Substack owner handle, echoed back in the verdict')
    name: typing.Optional[str] = Field(default=None, description='Publication name')
    description: typing.Optional[str] = Field(default=None, description='Publication hero text and/or author bio, if known')

class ProfileVerdict(BaseModel):
    handle: typing.Optional[str] = Field(default=None, description='Must exactly match the input handle')
    isAiRelated: typing.Optional[bool] = None
    confidence: typing.Optional[int] = Field(default=None, description='0-100 confidence that AI/ML/LLMs is the PRIMARY focus')

class ScoredArticle(BaseModel):
    url: typing.Optional[str] = None
    score: typing.Optional[int] = Field(default=None, description='1-100 developer-actionability rating')

class SearchCandidate(BaseModel):
    title: typing.Optional[str] = None
    url: typing.Optional[str] = None
    snippet: typing.Optional[str] = None

class SummarizeAndCategorizeResult(BaseModel):
    summary: typing.Optional[str] = Field(default=None, description='2-3 short factual lines separated by \\n')
    categories: typing.List[types.ArticleCategory] = Field(description='1-2 categories')
    kind: typing.Optional[types.ArticleKind] = None

class TitleFix(BaseModel):
    url: typing.Optional[str] = Field(default=None, description='The exact URL from the matching input article - copy verbatim')
    title: typing.Optional[str] = Field(default=None, description='Plain title text only. No surrounding quotes. No leading source name or bracket tag. Max 12 words. Return the input title verbatim if it is already clear, specific, and informative.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
