/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ArticleCategory,  ArticleInput,  ArticleKind,  CategorizeOnlyResult,  ClassifyKindResult,  DedupMatch,  ExistingArticle,  ExtractedLink,  NewsletterProduct,  ProductLinkChoice,  ProfileInput,  ProfileVerdict,  ScoredArticle,  SearchCandidate,  SummarizeAndCategorizeResult,  TitleFix } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ArticleInput {
      url?: string | null
      title?: string | null
      source?: string | null
      snippet?: string | null
      trust?: string | null
    }
    export interface CategorizeOnlyResult {
      categories: types.ArticleCategory[]
    }
    export interface ClassifyKindResult {
      kind?: types.ArticleKind | null
    }
    export interface DedupMatch {
      url?: string | null
      existingUrl?: string | null
    }
    export interface ExistingArticle {
      url?: string | null
      title?: string | null
      source?: string | null
    }
    export interface ExtractedLink {
      title?: string | null
      url?: string | null
      snippet?: string | null
    }
    export interface NewsletterProduct {
      name?: string | null
      description?: string | null
    }
    export interface ProductLinkChoice {
      index?: number | null
      confidence?: number | null
    }
    export interface ProfileInput {
      handle?: string | null
      name?: string | null
      description?: string | null
    }
    export interface ProfileVerdict {
      handle?: string | null
      isAiRelated?: boolean | null
      confidence?: number | null
    }
    export interface ScoredArticle {
      url?: string | null
      score?: number | null
    }
    export interface SearchCandidate {
      title?: string | null
      url?: string | null
      snippet?: string | null
    }
    export interface SummarizeAndCategorizeResult {
      summary?: string | null
      categories: types.ArticleCategory[]
      kind?: types.ArticleKind | null
    }
    export interface TitleFix {
      url?: string | null
      title?: string | null
    }
}