/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ArticleCategory {
  Models = "Models",
  Dev = "Dev",
  Research = "Research",
}

export enum ArticleKind {
  Repo = "Repo",
  Paper = "Paper",
  Model = "Model",
  Blog = "Blog",
  Product = "Product",
  Announcement = "Announcement",
}

export interface ArticleInput {
  url: string
  title: string
  source: string
  snippet?: string | null
  trust?: string | null
  
}

export interface CategorizeOnlyResult {
  categories: ArticleCategory[]
  
}

export interface ClassifyKindResult {
  kind: ArticleKind
  
}

export interface DedupMatch {
  url: string
  existingUrl: string
  
}

export interface ExistingArticle {
  url: string
  title: string
  source: string
  
}

export interface ExtractedLink {
  title: string
  url: string
  snippet: string
  
}

export interface NewsletterProduct {
  name: string
  description: string
  
}

export interface ProductLinkChoice {
  index: number
  confidence: number
  
}

export interface ProfileInput {
  handle: string
  name: string
  description?: string | null
  
}

export interface ProfileVerdict {
  handle: string
  isAiRelated: boolean
  confidence: number
  
}

export interface ScoredArticle {
  url: string
  score: number
  
}

export interface SearchCandidate {
  title: string
  url: string
  snippet: string
  
}

export interface SummarizeAndCategorizeResult {
  summary: string
  categories: ArticleCategory[]
  kind: ArticleKind
  
}

export interface TitleFix {
  url: string
  title: string
  
}
