/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    ArticleInput: ClassViewer<'ArticleInput', "url" | "title" | "source" | "snippet" | "trust">;
    
    CategorizeOnlyResult: ClassViewer<'CategorizeOnlyResult', "categories">;
    
    ClassifyKindResult: ClassViewer<'ClassifyKindResult', "kind">;
    
    DedupMatch: ClassViewer<'DedupMatch', "url" | "existingUrl">;
    
    ExistingArticle: ClassViewer<'ExistingArticle', "url" | "title" | "source">;
    
    ExtractedLink: ClassViewer<'ExtractedLink', "title" | "url" | "snippet">;
    
    NewsletterProduct: ClassViewer<'NewsletterProduct', "name" | "description">;
    
    ProductLinkChoice: ClassViewer<'ProductLinkChoice', "index" | "confidence">;
    
    ProfileInput: ClassViewer<'ProfileInput', "handle" | "name" | "description">;
    
    ProfileVerdict: ClassViewer<'ProfileVerdict', "handle" | "isAiRelated" | "confidence">;
    
    ScoredArticle: ClassViewer<'ScoredArticle', "url" | "score">;
    
    SearchCandidate: ClassViewer<'SearchCandidate', "title" | "url" | "snippet">;
    
    SummarizeAndCategorizeResult: ClassViewer<'SummarizeAndCategorizeResult', "summary" | "categories" | "kind">;
    
    TitleFix: ClassViewer<'TitleFix', "url" | "title">;
    
    
    ArticleCategory: EnumViewer<'ArticleCategory', "Models" | "Dev" | "Research">;
    
    ArticleKind: EnumViewer<'ArticleKind', "Repo" | "Paper" | "Model" | "Blog" | "Product" | "Announcement">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "ArticleInput","CategorizeOnlyResult","ClassifyKindResult","DedupMatch","ExistingArticle","ExtractedLink","NewsletterProduct","ProductLinkChoice","ProfileInput","ProfileVerdict","ScoredArticle","SearchCandidate","SummarizeAndCategorizeResult","TitleFix",
          ]),
          enums: new Set([
            "ArticleCategory","ArticleKind",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.ArticleInput = this.tb.classViewer("ArticleInput", [
          "url","title","source","snippet","trust",
        ]);
        
        this.CategorizeOnlyResult = this.tb.classViewer("CategorizeOnlyResult", [
          "categories",
        ]);
        
        this.ClassifyKindResult = this.tb.classViewer("ClassifyKindResult", [
          "kind",
        ]);
        
        this.DedupMatch = this.tb.classViewer("DedupMatch", [
          "url","existingUrl",
        ]);
        
        this.ExistingArticle = this.tb.classViewer("ExistingArticle", [
          "url","title","source",
        ]);
        
        this.ExtractedLink = this.tb.classViewer("ExtractedLink", [
          "title","url","snippet",
        ]);
        
        this.NewsletterProduct = this.tb.classViewer("NewsletterProduct", [
          "name","description",
        ]);
        
        this.ProductLinkChoice = this.tb.classViewer("ProductLinkChoice", [
          "index","confidence",
        ]);
        
        this.ProfileInput = this.tb.classViewer("ProfileInput", [
          "handle","name","description",
        ]);
        
        this.ProfileVerdict = this.tb.classViewer("ProfileVerdict", [
          "handle","isAiRelated","confidence",
        ]);
        
        this.ScoredArticle = this.tb.classViewer("ScoredArticle", [
          "url","score",
        ]);
        
        this.SearchCandidate = this.tb.classViewer("SearchCandidate", [
          "title","url","snippet",
        ]);
        
        this.SummarizeAndCategorizeResult = this.tb.classViewer("SummarizeAndCategorizeResult", [
          "summary","categories","kind",
        ]);
        
        this.TitleFix = this.tb.classViewer("TitleFix", [
          "url","title",
        ]);
        
        
        this.ArticleCategory = this.tb.enumViewer("ArticleCategory", [
          "Models","Dev","Research",
        ]);
        
        this.ArticleKind = this.tb.enumViewer("ArticleKind", [
          "Repo","Paper","Model","Blog","Product","Announcement",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}